### ISSUE TITLE
Deploy on Github Pages

### ISSUE THREAD

**Issue by bambadiagne** [daoodaba975/html.tricks#1]
Hey master!, nice tips🚀 but can you deploy it on GitHub Pages for more impact and visibility ?

**Comment by daoodaba975** [comment]
Hello @bambadiagne 
Yes why not?

I will make some update and deploy it!

**Comment by daoodaba975** [comment]
Thanks !

**Comment by bambadiagne** [comment]
> Hello @bambadiagne Yes why not?
> 
> I will make some update and deploy it!

OK thanks🥳

**Comment by daoodaba975** [comment]
Finally done @bambadiagne https://htmltricks.vercel.app 🎊

**Comment by bambadiagne** [comment]
> Finally done @bambadiagne https://htmltricks.vercel.app 🎊

Well done, I love UX so much✅

**Comment by daoodaba975** [comment]
Yes I did it in a simple way to stay in the HTML spirit 😁

> > Finally done @bambadiagne https://htmltricks.vercel.app 🎊
> 
> Well done, I love UX so much✅
